POST http://localhost:3000/V1/Task2/Insert/ColumnExist
Content-Type: application/json

{
  "StudentName": "",
  "Mobile": "",
  "Email": "",
  "CollegeName": "",
  "YearPassOut": "",
  "RollNumber": "",
  "GitLink": "",
  "HostLink": ""
}
